# docker-compose.dev-testing.yml
version: '3.8'

volumes:
  voice_core_dev_postgres_data: {}
  voice_core_dev_postgres_data_backups: {}
  voice_core_dev_redis_data: {}
  voice_core_dev_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev-testing/django/Dockerfile
    image: voice_core_dev_django
    container_name: voice_core_dev_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
      - ~/.aws:/root/.aws:ro  # ← Mount to standard AWS location
    env_file:
      - ./.envs/.dev-testing/.django
      - ./.envs/.dev-testing/.postgres
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: voice_core_dev_postgres
    container_name: voice_core_dev_postgres
    volumes:
      - voice_core_dev_postgres_data:/var/lib/postgresql/data
      - voice_core_dev_postgres_data_backups:/backups
    env_file:
      - ./.envs/.dev-testing/.postgres
    ports:
      - '5433:5432'
    restart: unless-stopped

  redis:
    image: docker.io/redis:6
    container_name: voice_core_dev_redis
    volumes:
      - voice_core_dev_redis_data:/data
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/dev-testing/traefik/Dockerfile
    image: voice_core_dev_traefik
    container_name: voice_core_dev_traefik
    depends_on:
      - django
    volumes:
      - voice_core_dev_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:5555:5555'
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: voice_core_dev_celeryworker
    container_name: voice_core_dev_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: voice_core_dev_celerybeat
    container_name: voice_core_dev_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
    restart: unless-stopped

  flower:
    <<: *django
    image: voice_core_dev_flower
    container_name: voice_core_dev_flower
    depends_on:
      - redis
      - postgres
    command: /start-flower
    restart: unless-stopped