# Generated by Django 5.1.10 on 2025-06-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cognito_sub',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=128, unique=True, verbose_name='Cognito User ID'),
            preserve_default=False,
        ),
    ]
