# Generated by Django 5.1.10 on 2025-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wazo_provisioned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wazo Provisioned At'),
        ),
        migrations.AddField(
            model_name='user',
            name='wazo_user_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Wazo User ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wazo_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wazo Username'),
        ),
    ]
