# Generated by Django 5.1.10 on 2025-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wazo_provisioned_at_user_wazo_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
