# Generated by Django 5.1.10 on 2025-08-20 05:44

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('extension', models.CharField(max_length=20, unique=True)),
                ('sip_username', models.CharField(max_length=50, unique=True)),
                ('sip_password', models.CharField(max_length=128)),
                ('line_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extension Assignment',
                'verbose_name_plural': 'Extension Assignments',
            },
        ),
    ]
