# Generated by Django 5.1.10 on 2025-08-20 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_extensionassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionassignment',
            name='context_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
