# Generated by Django 5.1.10 on 2025-08-20 07:44

import voice_core.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_extensionassignment_context_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionassignment',
            name='sip_password',
            field=voice_core.users.models.EncryptedCharField(max_length=128),
        ),
    ]
