# Generated by Django 5.1.10 on 2025-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_extensionassignment_sip_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionassignment',
            name='extension',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='extensionassignment',
            name='sip_username',
            field=models.CharField(max_length=50),
        ),
    ]
