# Generated by Django 5.1.10 on 2025-08-20 10:40

import voice_core.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_extensionassignment_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionassignment',
            name='sip_username',
            field=voice_core.users.models.EncryptedCharField(max_length=128),
        ),
    ]
