# Generated by Django 5.1.10 on 2025-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_extensionassignment_sip_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extensionassignment',
            old_name='line_id',
            new_name='wazo_line_id',
        ),
        migrations.AddField(
            model_name='extensionassignment',
            name='voicemail_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable voicemail for this extension'),
        ),
        migrations.AddField(
            model_name='extensionassignment',
            name='voicemail_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionassignment',
            name='voicemail_pin',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric PIN for accessing voicemail', null=True),
        ),
    ]
