# Generated by Django 5.1.10 on 2025-08-28 12:54

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionassignment',
            name='voicemail_enabled',
        ),
        migrations.RemoveField(
            model_name='extensionassignment',
            name='voicemail_id',
        ),
        migrations.RemoveField(
            model_name='extensionassignment',
            name='voicemail_pin',
        ),
        migrations.CreateModel(
            name='VoicemailAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('voicemail_id', models.IntegerField(blank=True, null=True)),
                ('voicemail_pin', models.PositiveIntegerField(blank=True, help_text='Numeric PIN for accessing voicemail', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voicemail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voicemail Assignment',
                'verbose_name_plural': 'Voicemail Assignments',
            },
        ),
    ]
