# Generated by Django 5.1.10 on 2025-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='wazo_tenant_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
