# Generated by Django 5.1.10 on 2025-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant_wazo_tenant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_users',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
