# Generated by Django 5.1.10 on 2025-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_tenant_max_users_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contexts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
