#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

# Use gunicorn with reload for development-like experience
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --workers=2 --reload --timeout=120